version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpwd
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ../../mount/postgres/data:/var/lib/postgresql/data
      
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpw
    ports:
      - "80:80"
    volumes:
      - ../../mount/postgres/pgadmin:/var/lib/pgadmin

